# Generated by Django 4.1 on 2024-01-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('requisitos', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/core/img/beneficios/')),
            ],
        ),
        migrations.CreateModel(
            name='Ferreteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('caracteristicas', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/core/img/ferreteria/')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Aseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('caracteristicas', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/core/img/aseo/')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Adhesivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('caracteristicas', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/core/img/adhesivos/')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etiqueta')),
            ],
        ),
    ]
