# Generated by Django 4.1 on 2024-01-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiqueta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='etiqueta',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='etiqueta',
            name='requisitos',
        ),
    ]
