# Generated by Django 4.1 on 2024-01-06 20:13

from django.db import migrations, models
import django.db.models.fields.reverse_related


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_etiqueta_descripcion_remove_etiqueta_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesivo',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.fields.reverse_related.ManyToOneRel, to='core.etiqueta'),
        ),
    ]
