# Generated by Django 4.1 on 2024-01-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_adhesivo_etiqueta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferreteria',
            name='etiqueta',
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='etiquetas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.etiqueta'),
        ),
    ]
