# Generated by Django 4.1 on 2024-01-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ferreteria_etiqueta_ferreteria_etiquetas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etiqueta',
            new_name='Categoria',
        ),
    ]
