# Generated by Django 4.1 on 2024-01-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_etiqueta_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adhesivo',
            old_name='etiqueta',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='aseo',
            old_name='etiqueta',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='ferreteria',
            old_name='etiquetas',
            new_name='categoria',
        ),
    ]
