# Generated by Django 4.1 on 2024-01-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_etiqueta_adhesivo_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aseo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='ferreteria',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Adhesivo',
        ),
        migrations.DeleteModel(
            name='Aseo',
        ),
    ]
