# Generated by Django 4.1 on 2024-01-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_aseo_categoria_ferreteria_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferreteria',
            name='precio_unidad',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ferreteria',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
