# Generated by Django 4.1 on 2024-01-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ferreteria_precio_unidad_alter_ferreteria_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferreteria',
            name='imagen',
            field=models.ImageField(upload_to='static/core/img/ferreteria/'),
        ),
    ]
