# Generated by Django 4.1 on 2024-01-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ferreteria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferreteria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='ferreteria'),
        ),
    ]
