# Generated by Django 4.1 on 2024-01-10 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ferreteria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('caracteristicas', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='aseo')),
                ('precio', models.DecimalField(decimal_places=0, default=0.0, max_digits=10)),
                ('precio_unidad', models.DecimalField(decimal_places=0, default=0.0, max_digits=10)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Adhesivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('caracteristicas', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='adhesivos')),
                ('precio', models.DecimalField(decimal_places=0, default=0.0, max_digits=10)),
                ('precio_unidad', models.DecimalField(decimal_places=0, default=0.0, max_digits=10)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
            ],
        ),
    ]
