# Generated by Django 4.1 on 2025-01-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aseo_adhesivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhesivo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='aseo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ferreteria',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
